Description: >
  This template creates task execution role for running application in ECS cluster.

Parameters:

  EnvironmentName:
    Description: An environment name that will be prefixed to resource names
    Type: String

  AppName:
    Type: String
    Description: App name

  TaskExecutionRoleName:
    Description: Please provide task execution role name
    Type: String
    Default: sample-ENV-APP-ecsTaskExecutionRole

Resources:

  TaskExecutionIamRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Ref TaskExecutionRoleName
      Path: /
      AssumeRolePolicyDocument: |
        {
            "Statement": [{
                "Effect": "Allow",
                "Principal": { "Service": [ "ecs-tasks.amazonaws.com" ]},
                "Action": [ "sts:AssumeRole" ]
            }]
        }
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy

Outputs:

    TaskExecutionIamRoleArn:
      Description: Task Executin IAM role used by ECS tasks
      Value: { "Fn::GetAtt": TaskExecutionIamRole.Arn }
      Export:
        Name: !Sub "${EnvironmentName}-${AppName}:TaskExecutionIamRoleArn"
